# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  python-linting-code:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        uses: super-linter/super-linter@v5.7.2
        
